#!/bin/bash
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" -d "$POSTGRES_DB"  <<-EOSQL
     CREATE SCHEMA IF NOT EXISTS lab1;
     CREATE TABLE lab1.mock_data (
        id INTEGER,
        customer_first_name VARCHAR(50),
        customer_last_name VARCHAR(50),
        customer_age SMALLINT,
        customer_email VARCHAR(50),
        customer_country VARCHAR(50),
        customer_postal_code VARCHAR(50),
        customer_pet_type VARCHAR(50),
        customer_pet_name VARCHAR(50),
        customer_pet_breed VARCHAR(50),
        seller_first_name VARCHAR(50),
        seller_last_name VARCHAR(50),
        seller_email VARCHAR(50),
        seller_country VARCHAR(50),
        seller_postal_code VARCHAR(50),
        product_name VARCHAR(50),
        product_category VARCHAR(50),
        product_price MONEY,
        product_quantity INTEGER,
        sale_date DATE,
        sale_customer_id INTEGER,
        sale_seller_id INTEGER,
        sale_product_id INTEGER,
        sale_quantity INTEGER,
        sale_total_price MONEY,
        store_name VARCHAR(50),
        store_location VARCHAR(50),
        store_city VARCHAR(50),
        store_state VARCHAR(50),
        store_country VARCHAR(50),
        store_phone VARCHAR(50),
        store_email VARCHAR(50),
        pet_category VARCHAR(50),
        product_weight DOUBLE PRECISION,
        product_color VARCHAR(50),
        product_size VARCHAR(50),
        product_brand VARCHAR(50),
        product_material VARCHAR(50),
        product_description TEXT,
        product_rating DOUBLE PRECISION,
        product_reviews INTEGER,
        product_release_date DATE,
        product_expiry_date DATE,
        supplier_name VARCHAR(50),
        supplier_contact VARCHAR(50),
        supplier_email VARCHAR(50),
        supplier_phone VARCHAR(50),
        supplier_address VARCHAR(50),
        supplier_city VARCHAR(50),
        supplier_country VARCHAR(50)
     );
EOSQL
